# Generated by Django 3.0.8 on 2023-02-05 18:08

import api.annonces.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('localisation', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.TextField()),
                ('prix', models.CharField(blank=True, max_length=20, null=True)),
                ('surface', models.CharField(blank=True, max_length=20, null=True)),
                ('date_publication', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('categorie_immobilier', models.CharField(blank=True, choices=[('Vente', 'Vente'), ('Echange', 'Echange'), ('Location', 'Location'), ('Location pour vacance', 'Location pour vacance')], default='Vente', max_length=25, null=True)),
                ('type_immobilier', models.CharField(blank=True, choices=[('Terrain', 'Terrain'), ('Terrain Agricole', 'Terrain Agricole'), ('Appartement', 'Appartement'), ('Maison', 'Maison'), ('Bungalow', 'Bungalow')], default='Appartement', max_length=25, null=True)),
                ('unite_prix', models.CharField(blank=True, choices=[('Da', 'Da'), ('Million centime', 'Million centime'), ('Milliard centime', 'Milliard centime'), ('DA par m2', 'DA par m2'), ('Million par m2', 'Million par m2')], default='Da', max_length=25, null=True)),
                ('adresse_bien_immobilier', models.CharField(blank=True, max_length=200, null=True)),
                ('id_immobilier', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('vendu', models.BooleanField(blank=True, default=False, null=True)),
                ('public', models.BooleanField(blank=True, default=False, null=True)),
                ('obtenu_webscraping', models.BooleanField(default=False)),
                ('parking', models.BooleanField(blank=True, default=False, null=True)),
                ('terrasse', models.BooleanField(blank=True, default=False, null=True)),
                ('garage', models.BooleanField(blank=True, default=False, null=True)),
                ('meuble', models.BooleanField(blank=True, default=False, null=True)),
                ('eau', models.BooleanField(blank=True, default=False, null=True)),
                ('gaz', models.BooleanField(blank=True, default=False, null=True)),
                ('electricite', models.BooleanField(default=False)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='localisation.Commune')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.Contact')),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='localisation.Wilaya')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAnnonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=api.annonces.models.upload_to)),
                ('id_annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.Annonce')),
            ],
        ),
    ]
