# Generated by Django 3.0.8 on 2023-02-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
