# Generated by Django 3.0.8 on 2023-02-05 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur_id', models.IntegerField()),
                ('nom', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='localisation.Commune')),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='localisation.Wilaya')),
            ],
        ),
    ]
